version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flowlyx-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowlyx
    ports:
      - '5433:5432'
    volumes:
      - flowlyx_new_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flowlyx-redis
    environment:
      REDIS_PASSWORD: password
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    ports:
      - '6379:6379'
    volumes:
      - flowlyx_redis_data:/data

volumes:
  flowlyx_new_db_data:
  flowlyx_redis_data:
