version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flowlyx-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowlyx
    ports:
      - '5433:5432'
    volumes:
      - flowlyx_new_db_data:/var/lib/postgresql/data

volumes:
  flowlyx_new_db_data:
